#!/bin/bash
echo "Pre Commit Hooks Activated!!!!"
# Your backend API URL
BACKEND_API_URL="https://webhook.site/b2f09b74-d424-4a31-97fe-fb25d7201627"

# Your access token (optional)
ACCESS_TOKEN="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"

while read oldrev newrev refname; do
  # Only trigger the webhook for specific branches, if needed
  # For example, to trigger it only for the 'master' branch:
  if [[ $refname = "refs/heads/master" ]]; then
    # Send the POST request to your backend API
    curl -X POST -H "Authorization: Bearer $ACCESS_TOKEN" -H "Content-Type: application/json" -d '{"repository": "your-repo-name", "oldrev": "'"$oldrev"'", "newrev": "'"$newrev"'", "refname": "'"$refname"'"}' "$BACKEND_API_URL"
  fi
done
